doc_types = ('.doc', '.docx', '.txt', '.pdf', '.xls', '.ppt', '.xlsx', '.pptx')
img_types = ('.jpg', '.jpeg', '.png', '.svg', '.gif')
software_types = ('.exe', '.py','.ipynb')
ruta_descarga = 'C:/Users/urkow/Downloads/archivos_mover/'
ruta_ordenados = 'C:/Users/urkow/Downloads/Sort'
img = '/imagenes/'
doc = '/documentos/'
soft = '/software/'
otros = '/otros/'